name: mis_tools
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.1.0
  ansicolor: ^2.0.1
  colorize: ^3.0.0
  dart_console: ^1.2.0
  console: ^4.1.0
  dcache: ^0.4.0
  uuid: ^3.0.4
  tuple: ^2.0.0
  meta: ^1.2.4
  yaml: ^3.1.0
  cli_repl: ^0.2.2
  intl: ^0.18.0
  postgres: ^2.2.0
  easy_isolate:
    git:
      url: https://github.com/kjelly/easy_isolate
      ref: main
  dart_amqp: ^0.2.1
  collection: ^1.15.0
  markdown: ^7.0.0
  format: ^1.3.0
  fuzzywuzzy: ^0.2.0
  logger: ^1.1.0
  logging: ^1.0.2
  shelf: ^1.3.1

dev_dependencies:
  lints: ^2.1.0
